### PR TITLE
Add PHP alias to execute specific to virtual server PHP version

### PR DESCRIPTION
**Pull request by iliaross**
Ref.: https://github.com/virtualmin/virtualmin-gpl/issues/520#issuecomment-1562768420

### CODE REVIEW

**Comment by jcameron** [comment]
Can you post the generated bashrc config that this creates? It's hard to understand with all those backquotes!

**Comment by iliaross** [comment]
> Can you post the generated bashrc config that this creates? It's hard to understand with all those backquotes!

Yes, sure. Check this out:

```
if php -v 1>/dev/null 2>&1; then
  alias php='$(phpdom="bin/php" ; phpdef="/bin/php" ; (while [ ! -f "$phpdom" ] && [ "$PWD" != "/" ]; do cd "$(dirname "$PWD")" || "$phpdef" ; done ; if [ -f "$phpdom" ] ; then echo "$PWD/$phpdom" ; else echo "$phpdef" ; fi))'
fi
```

It's both _Sh_ and _Bash_ friendly.

**Comment by iliaross** [comment]
> Can you post the generated bashrc config that this creates?

Although, this is `/etc/profile.d/virtualmin-phpalias.sh` and is not `.bashrc` config, which is infact will be able to override our `virtualmin-phpalias.sh`. I don't think it would be right (best option) to add changes to user's `.bashrc` really.

**Comment by iliaross** [comment]
> I don't think it would be right (best option) to add changes to user's `.bashrc` really.

And it could be plenty of them.

**Comment by jcameron** [comment]
Ah I see ... so it searches up from the current directory for a `bin/php` command. One suggestion though - the default should be more flexible than just assuming `/bin/php` , because it might be in `/usr/bin/php` or elsewhere in the path.

**Comment by iliaross** [comment]
> One suggestion though - the default should be more flexible than just assuming `/bin/php` , because it might be in `/usr/bin/php` or elsewhere in the path.

Yes, great suggestion. Fixed here https://github.com/virtualmin/Virtualmin-Config/pull/16/commits/3dc276fc7a423bf47f86c70d38778edee50fbb12.

**Comment by iliaross** [comment]
Jamie, let's factor this new code to a separate sub in Virtualmin, and run it on existing systems when creating `~/bin/php` or config check .. ? people are asking for this feature .. If you don't mind I'll go for it?

**Comment by jcameron** [comment]
Sure, please send me a PR for this..

**Comment by iliaross** [comment]
Sure, will do!

**Comment by iliaross** [comment]
> Sure, please send me a PR for this..

[PR](https://github.com/virtualmin/virtualmin-gpl/pull/584/files) is sent.

**Pull request merged**
