### PR TITLE
Fix `backend` to use `systemd`

### PR DESCRIPTION
**Pull request by iliaross**
Switch backend to use systemd to avoid failure on `fail2ban` starting when actual log file is missing

**Error example:**

```
root@ubuntu22-gpl:~# systemctl status fail2ban
× fail2ban.service - Fail2Ban Service
     Loaded: loaded (/etc/systemd/system/fail2ban.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2022-04-09 22:45:38 UTC; 3s ago
       Docs: man:fail2ban(1)
    Process: 165392 ExecStart=/usr/bin/fail2ban-server -xf start (code=exited, status=255/EXCEPTION)
   Main PID: 165392 (code=exited, status=255/EXCEPTION)
        CPU: 102ms

Apr 09 22:45:38 ubuntu22-gpl.local systemd[1]: Started Fail2Ban Service.
Apr 09 21:56:59 ubuntu22-gpl.local fail2ban-server[155217]: 2022-04-09 21:56:59,748 fail2ban                [155217]: ERROR   Failed during configuration: Have not found any log file for sshd jail
Apr 09 22:45:38 ubuntu22-gpl.local fail2ban-server[165392]: 2022-04-09 22:45:38,898 fail2ban                [165392]: ERROR   Failed during configuration: Have not found any log file for postfix jail
Apr 09 22:45:38 ubuntu22-gpl.local fail2ban-server[165392]: 2022-04-09 22:45:38,901 fail2ban                [165392]: ERROR   Async configuration of server failed

```

### CODE REVIEW

**Comment by iliaross** [comment]
@swelljoe @jcameron Any thoughts about this PR?

**Comment by jcameron** [comment]
Will this still work if the system isn't using `systemd` ?

**Comment by iliaross** [comment]
This is why it's a PR. 🙂  I am not sure. All systems use `systemd` nowadays?

**Comment by iliaross** [comment]
.. but it seems the only best option for Virtualmin 7 to work out of the box with newer distros ..

**Comment by swelljoe** [comment]
All distros currently supported by the Virtualmin installer use systemd (we're a few years past EOL for distros that used something else...Ubuntu 14.04 and CentOS 6 were the last non-systemd distros). I'm not particularly inclined to jump through hoops to support non-systemd systems.

Can you link to docs that explain why this is useful/necessary? What distro does the problem this solves happen on?

**Comment by jcameron** [comment]
Ok, in that case, just supporting systemd is fine.

**Comment by iliaross** [comment]
It was discussed few times, and here is one of the [posts](https://github.com/fail2ban/fail2ban/issues/2756) on fail2ban repo. The other posts mentioned that just creating missing log file "solved" the problem for them as well. I didn't like that solution though.

I tried it on Ubuntu 22.04 and CentOS 9 Stream. Perhaps, `rsyslog` package is not installed by default. Do we need mentioning `rsyslog` package on Virtualmin stack packages?

**Comment by iliaross** [comment]
I suggest merging it.

**Pull request merged**
